server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: my-pc
    username: shop
    password: 123
    virtual-host: /shop
  redis:
    host: my-pc

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

sms:
  accessKeyId: LTAI4FfTW1n5TMkVqq4cxZbN
  accessKeySecret: 9W3T2vLaX83KMwWFi9KGkS9sNBppBW
  sigName: 转笔圈
  template: SMS_174991381